name: jupyterjax
channels:
  - conda-forge
  - defaults
  - nvidia/label/cuda-11.8.0
dependencies:
  - python=3.10
  - jax
  - numpy
  - matplotlib
  - pandas
  - scipy
  - scikit-learn
  - xonsh
  - ipykernel
  - jupyterlab
  - pytorch-cuda=11.8
  - cudatoolkit=11.8
  - openai
  - mpi4py
  - beautifulsoup4
  - sqlite3
  - cypress
  - requests
  - sympy
  - cython
  - mpi4py
  - lld


env:
  DATABASE_URL: sqlite:///db.sqlite3
  ENV_DICT: []
  ENV_KEYS: []
  ENV_VALUES: []
  ENV_VECTORS: []
  ENV_VECTORS_VALUES: []
  process_id: INT
  thread_id: INT
  tstatus_id: INT
  pstatus_id: INT
  thread_process_status: ""
  dev_ids: []
  inodes: []
  promises: []
  ENV_session_id: ""
  ENV_ip: ""
  ENV_port: ""
  ENV_credentials: []
  ENV_embeddings: ""
  ENV_entbeddings: ""
  ENV_worker_status: ""
  ENV_workerid: ""
  ENV_task_status: ""
  ENV_taskid: ""
